In [1]:
from tool import *

In [2]:
with open('D:/Data/TCL box.bin', 'rb') as f:
    box = pickle.load(f)

## 1. 신규 박스 요청 정보 추가

In [15]:
# 박스 요청 정보 입력
신청일 = '2024-01-11'
사이트 = 'EACM'
모델명 = '27MR400.AKRQ'
수량 = 20

In [34]:
new_request = pd.read_clipboard()
new_request

,Request Date,To Site,Mapping Model.Suffix,QTY,Shipment Schedule,B/L Number,Container Number
0,2024-01-11,EACM,22MR410-B.APHQ,22,NaN,NaN,NaN
1,2024-01-11,EACM,24MR400-B.APHQ,30,NaN,NaN,NaN

In [37]:
box = pd.concat([box, new_request]).reset_index(drop=True)

In [38]:
box

,Request Date,To Site,Mapping Model.Suffix,QTY,Shipment Schedule,B/L Number,Container Number
0,2023-11-14,ENCI,22MR410-B.AUSQ,20,Ship with 11/27W shipping batch,PLISZ4E13545,MRKU8876626
1,2023-11-08,EATH,22MR410-B.ATMQ,40,Ship with 11/27W shipping batch,PLISZ4E13560,FBIU0292678
2,2023-11-08,EATH,27MR400-B.ATMQ,20,Ship with 11/27W shipping batch,PLISZ4E13560,FBIU0292678
3,2023-11-08,EASL,27MR400-B.AHKQ,10,Ship with 11/27W shipping batch,PLISZ4E13682,FCIU6360956
4,2023-11-20,ENUS_V,27MR400-B.AUSQ,2,NaN,NaN,NaN
5,2023-12-18,EKHQ,22MR410.AKRQ,20,Ship with 1/8W shipping batch,PLISZ4F00301,NSSU7147311
6,2023-12-18,EKHQ,27MR400.AKRQ,20,Ship with 1/8W shipping batch,PLISZ4F00301,NSSU7147311
7,2024-01-11,EACM,22MR410-B.APHQ,22,NaN,NaN,NaN
8,2024-01-11,EACM,24MR400-B.APHQ,30,NaN,NaN,NaN

In [39]:
# DB 저장
with open('D:/Data/TCL box.bin', 'wb') as f:
    pickle.dump(box, f)

## 2. 박스 요청 건에 대한 공급 일정 업데이트

In [3]:
with open('D:/Data/TCL box.bin', 'rb') as f:
    box = pickle.load(f)

In [4]:
box

,Request Date,To Site,Mapping Model.Suffix,QTY,Shipment Schedule,B/L Number,Container Number
0,2023-11-14,ENCI,22MR410-B.AUSQ,20,Ship with 11/27W shipping batch,PLISZ4E13545,MRKU8876626
1,2023-11-08,EATH,22MR410-B.ATMQ,40,Ship with 11/27W shipping batch,PLISZ4E13560,FBIU0292678
2,2023-11-08,EATH,27MR400-B.ATMQ,20,Ship with 11/27W shipping batch,PLISZ4E13560,FBIU0292678
3,2023-11-08,EASL,27MR400-B.AHKQ,10,Ship with 11/27W shipping batch,PLISZ4E13682,FCIU6360956
4,2023-11-20,ENUS_V,27MR400-B.AUSQ,2,Ship with 1/15W shipping batch,NaN,NaN
5,2023-12-18,EKHQ,22MR410.AKRQ,20,Ship with 1/8W shipping batch,PLISZ4F00301,NSSU7147311
6,2023-12-18,EKHQ,27MR400.AKRQ,20,Ship with 1/8W shipping batch,PLISZ4F00301,NSSU7147311
7,2024-01-11,EACM,22MR410-B.APHQ,22,Ship with 2/5W shipping batch,NaN,NaN
8,2024-01-11,EACM,24MR400-B.APHQ,30,Ship with 2/5W shipping batch,NaN,NaN

In [5]:
updated_schedule = pd.read_clipboard() # 엑셀에서 업데이트한 내용을 복사해서 clipboard에서 읽어옴
updated_schedule

,Request Date,To Site,Mapping Model.Suffix,QTY,Shipment Schedule,B/L Number,Container Number
0,2023-11-20,ENUS_V,27MR400-B.AUSQ,2,Ship with 1/15W shipping batch,PLISZ4F00772,MRKU2519257

In [6]:
updated_schedule = updated_schedule.set_index(['Request Date', 'To Site', 'Mapping Model.Suffix', 'QTY'])

In [7]:
box = box.set_index(['Request Date', 'To Site', 'Mapping Model.Suffix', 'QTY'])

In [8]:
box.update(updated_schedule)

In [9]:
box

                                                             Shipment Schedule  \
Request Date To Site Mapping Model.Suffix QTY
2023-11-14   ENCI    22MR410-B.AUSQ       20   Ship with 11/27W shipping batch
2023-11-08   EATH    22MR410-B.ATMQ       40   Ship with 11/27W shipping batch
                     27MR400-B.ATMQ       20   Ship with 11/27W shipping batch
             EASL    27MR400-B.AHKQ       10   Ship with 11/27W shipping batch
2023-11-20   ENUS_V  27MR400-B.AUSQ       2     Ship with 1/15W shipping batch
2023-12-18   EKHQ    22MR410.AKRQ         20     Ship with 1/8W shipping batch
                     27MR400.AKRQ         20     Ship with 1/8W shipping batch
2024-01-11   EACM    22MR410-B.APHQ       22     Ship with 2/5W shipping batch
                     24MR400-B.APHQ       30     Ship with 2/5W shipping batch

                                                 B/L Number Container Number
Request Date To Site Mapping Model.Suffix QTY
2023-11-14   ENCI    22MR410-B.AUSQ       20   PLISZ4E13545      MRKU8876626
2023-11-08   EATH    22MR410-B.ATMQ       40   PLISZ4E13560      FBIU0292678
                     27MR400-B.ATMQ       20   PLISZ4E13560      FBIU0292678
             EASL    27MR400-B.AHKQ       10   PLISZ4E13682      FCIU6360956
2023-11-20   ENUS_V  27MR400-B.AUSQ       2    PLISZ4F00772      MRKU2519257
2023-12-18   EKHQ    22MR410.AKRQ         20   PLISZ4F00301      NSSU7147311
                     27MR400.AKRQ         20   PLISZ4F00301      NSSU7147311
2024-01-11   EACM    22MR410-B.APHQ       22            NaN              NaN
                     24MR400-B.APHQ       30            NaN              NaN

In [10]:
box = box.reset_index()

In [11]:
# DB 저장
with open('D:/Data/TCL box.bin', 'wb') as f:
    pickle.dump(box, f)