# Quanta가 보내주는 Input Plan 엑셀파일가공하여 DB에 업데이트

In [1]:
from tool import *
import pandas_bokeh

## 1. DB를 불러옴

In [2]:
with open('D:/Data/Quanta Input Plan.bin', 'rb') as f:
    input_df = pickle.load(f)

In [3]:
def make_summary(dataframe):
    df = dataframe.copy()
    df['Series'] = df['Mapping Model.Suffix'].apply(lambda x:x.split('-')[0]).replace(srt_model)
    return df.pivot_table('QTY', index='Series', columns='LG Week',aggfunc=sum).fillna(0)
    
def make_input_difference(df):
    d1 = df['Created_at'].unique()[-1]
    d2 = df['Created_at'].unique()[-2]
    c1 = (df['Created_at'] == d1)
    c2 = (df['Created_at'] == d2)
    df1 = input_df[c1]
    df2 = input_df[c2]
    df1 = make_summary(df1)
    df2 = make_summary(df2)
    return get_difference_table(df1, df2, '-\d\d-')

## 2. Quanta Input Plan 불러옴

In [4]:
updated_date = datetime.date(2023,3,8) # 업데이트된 날짜 설정

In [5]:
input_df['Created_at'].unique()[-4:] # 최근 4번의 업데이트 일자 조회

array([datetime.date(2023, 3, 1), datetime.date(2023, 3, 2),
       datetime.date(2023, 3, 6), datetime.date(2023, 3, 7)], dtype=object)

In [6]:
path = get_filename()
df = pd.read_excel(path)
cond = (df.iloc[:, 1] == 'LGE P/N')
i_num = df.loc[cond].index[0]
df = pd.read_excel(path, skiprows=i_num+1)
df = df.drop('MODEL', axis = 1)
df = df[df['LGE P/N'].notnull()]
df = df[~df['Quanta P/N'].isnull()]
df.rename(columns={'LGE P/N':'Mapping Model.Suffix'}, inplace=True)
df.columns = df.columns.astype(str)

day_list = get_pattern_from_list(df.columns, re.compile('\d\d-\d\d'))
df = df[['Mapping Model.Suffix', 'Quanta P/N']+day_list]
df = df.convert_dtypes()
df = df.fillna(0)

df = df.set_index(['Mapping Model.Suffix', 'Quanta P/N'])
df = df.stack().reset_index()

In [7]:
df = df.rename(columns={'level_2':'Input Date', 0:'QTY'})
df['Input Date'] = pd.to_datetime(df['Input Date'])

df['LG Week'] = df['Input Date'].apply(get_weekname)
df = df[df['QTY'] != 0]
df = df.reset_index(drop=True)
df['Created_at'] = updated_date
df['QTY'] = df['QTY'].astype(int)
df['Mapping Model.Suffix'] = df['Mapping Model.Suffix'].str.strip()

In [8]:
df.shape

(116, 6)

In [9]:
input_df.shape

(22094, 6)

In [10]:
make_summary(df)

LG Week,2023-02-27(W09),2023-03-06(W10),2023-03-13(W11),2023-03-20(W12),2023-03-27(W13)
Series,,,,,
11T50Q,290.0,0.0,0.0,90.0,50.0
14T90Q,0.0,30.0,0.0,0.0,10.0
14T90R,0.0,10.0,415.0,770.0,255.0
15U40Q,0.0,0.0,0.0,0.0,50.0
15U40R,0.0,0.0,0.0,1319.0,1260.0
15U50P,0.0,0.0,0.0,0.0,190.0
15U50Q,0.0,1292.0,5218.0,0.0,1555.0
15U50R,0.0,90.0,0.0,0.0,110.0
16T90Q,500.0,120.0,125.0,0.0,445.0
16T90R,355.0,160.0,50.0,860.0,470.0

In [11]:
get_difference_table(make_summary(df), make_summary(input_df[(input_df['Created_at'] == input_df['Created_at'].max())]), '-\d\d-')

,2023-02-27(W09),2023-03-06(W10),2023-03-13(W11),2023-03-20(W12),2023-03-27(W13)
11T50Q,0,0,0,90,-90
14T90Q,0,0,0,0,0
14T90R,0,-140,-135,305,-155
15U40Q,0,0,0,0,0
15U40R,0,0,0,-1000,1260
15U50P,0,0,0,0,140
15U50Q,0,1292,-1292,0,1500
15U50R,0,0,0,0,100
16T90Q,0,0,0,0,0
16T90R,0,35,-35,-5,-325

In [12]:
input_df = pd.concat([input_df, df])
input_df.reset_index(drop=True, inplace=True)

In [13]:
input_df.shape

(22210, 6)

## 3. 최종 결과를 DB에 저장

In [14]:
with open('D:/Data/Quanta Input Plan.bin', 'wb') as f:
    pickle.dump(input_df, f)

In [15]:
with open('D:/Data/DB backup/Quanta Input Plan.bin', 'wb') as f:
    pickle.dump(input_df, f)

### OS별 Quanta 생산계획으로 출력

In [18]:
with open('D:/Data/Quanta Input Plan.bin', 'rb') as f:
    pr = pickle.load(f)

day = pr['Created_at'].max() # 최근일자의 생산계획 가져옴
print('조회일자 : {}'.format(day))
pr = pr[pr['Created_at']==day]

pr = pr.pivot_table('QTY', index=['Mapping Model.Suffix', 'Quanta P/N'], columns='LG Week', aggfunc='sum').fillna(0).reset_index()

col = ['Model.Suffix', 'OS TYPE']
# 클립보드로 붙여넣기
pr.merge(get_pdr()[col], left_on='Mapping Model.Suffix', right_on='Model.Suffix').drop(columns='Model.Suffix').groupby(['OS TYPE']).sum().to_clipboard()
pr.merge(get_pdr()[col], left_on='Mapping Model.Suffix', right_on='Model.Suffix').drop(columns='Model.Suffix').groupby(['OS TYPE', 'Mapping Model.Suffix', 'Quanta P/N']).sum()

조회일자 : 2023-01-06

                                                                   2023-01-02(W01)  \
OS TYPE                          Mapping Model.Suffix Quanta P/N
Chrome OS                        11TG50Q-E.AC10KN     1LI70000087                0
NON-OS                           15UD40Q-G.AX70K      1LGH0000076                0
                                 15UD50Q-G.AX30K      1LGHA000110              255
                                 15UD50Q-G.AX50K      1LGHA000105              889
                                 16TD90Q-G.AX56K      1NLJA000101                0
...                                                                            ...
WINDOWS 11 PRO WITH Downgrade FR 15U50Q-S.AS5KL       1LGHA000146                0
                                 15U50Q-S.AS5LL       1LGHA000138                0
                                 15U50Q-S.AS7DL       1LGHA000139                0
                                 15U50Q-S.AS7GL       1LGHA000140                0
                                 16T90Q-G.AS7WL       1NLJA000119                0

                                                                   2023-01-09(W02)  \
OS TYPE                          Mapping Model.Suffix Quanta P/N
Chrome OS                        11TG50Q-E.AC10KN     1LI70000087                0
NON-OS                           15UD40Q-G.AX70K      1LGH0000076                0
                                 15UD50Q-G.AX30K      1LGHA000110                0
                                 15UD50Q-G.AX50K      1LGHA000105                0
                                 16TD90Q-G.AX56K      1NLJA000101                0
...                                                                            ...
WINDOWS 11 PRO WITH Downgrade FR 15U50Q-S.AS5KL       1LGHA000146                1
                                 15U50Q-S.AS5LL       1LGHA000138                1
                                 15U50Q-S.AS7DL       1LGHA000139                1
                                 15U50Q-S.AS7GL       1LGHA000140                1
                                 16T90Q-G.AS7WL       1NLJA000119                0

                                                                   2023-01-16(W03)  \
OS TYPE                          Mapping Model.Suffix Quanta P/N
Chrome OS                        11TG50Q-E.AC10KN     1LI70000087                0
NON-OS                           15UD40Q-G.AX70K      1LGH0000076              224
                                 15UD50Q-G.AX30K      1LGHA000110              725
                                 15UD50Q-G.AX50K      1LGHA000105             1000
                                 16TD90Q-G.AX56K      1NLJA000101                0
...                                                                            ...
WINDOWS 11 PRO WITH Downgrade FR 15U50Q-S.AS5KL       1LGHA000146                0
                                 15U50Q-S.AS5LL       1LGHA000138                0
                                 15U50Q-S.AS7DL       1LGHA000139                0
                                 15U50Q-S.AS7GL       1LGHA000140                0
                                 16T90Q-G.AS7WL       1NLJA000119                0

                                                                   2023-01-23(W04)  \
OS TYPE                          Mapping Model.Suffix Quanta P/N
Chrome OS                        11TG50Q-E.AC10KN     1LI70000087                0
NON-OS                           15UD40Q-G.AX70K      1LGH0000076                0
                                 15UD50Q-G.AX30K      1LGHA000110                0
                                 15UD50Q-G.AX50K      1LGHA000105                0
                                 16TD90Q-G.AX56K      1NLJA000101                0
...                                                                            ...
WINDOWS 11 PRO WITH Downgrade FR 15U50Q-S.AS5KL       1LGHA000146                0
                                 15U50Q-S.AS5LL       1LGHA000138                0
                                 15U50Q-S.AS7DL       1LGHA000139                0
                                 15U50Q-S.AS7GL       1LGHA000140                0
                                 16T90Q-G.AS7WL       1NLJA000119                0

                                                                   2023-01-30(W05)
OS TYPE                          Mapping Model.Suffix Quanta P/N
Chrome OS                        11TG50Q-E.AC10KN     1LI70000087              780
NON-OS                           15UD40Q-G.AX70K      1LGH0000076                0
                                 15UD50Q-G.AX30K      1LGHA000110                0
                                 15UD50Q-G.AX50K      1LGHA000105             1000
                                 16TD90Q-G.AX56K      1NLJA000101              400
...                                                                            ...
WINDOWS 11 PRO WITH Downgrade FR 15U50Q-S.AS5KL       1LGHA000146               69
                                 15U50Q-S.AS5LL       1LGHA000138              149
                                 15U50Q-S.AS7DL       1LGHA000139              499
                                 15U50Q-S.AS7GL       1LGHA000140              499
                                 16T90Q-G.AS7WL       1NLJA000119               50

[80 rows x 5 columns]